# 将API数据下载为文件供Gitee/jsDelivr等镜像地址加速

name: "接收请求触发文件更新"

on:
  workflow_dispatch

jobs:

  download-api:
    name: "输出API数据至文件"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4

      - name: "ZIP_CDN加速目录数据"
        run: |
          curl -s https://api.github.com/repos/typecho-fans/plugins/contents/ZIP_CDN > ZIP_CDN.json

      - name: "文档最后更新时间字串"
        run: |
          date_testore=`curl -s "https://api.github.com/repos/typecho-fans/plugins/commits?path=TESTORE.md&page=1&per_page=1" | jq -r ".[0].commit.committer.date"`
          date_readme=`curl -s "https://api.github.com/repos/typecho-fans/plugins/commits?path=README.md&page=1&per_page=1" | jq -r ".[0].commit.committer.date"`
          if [ $date_testore -gt $date_readme ]; then
            echo $date_testore > UD_TIME.json
          else
            echo $date_readme > UD_TIME.json
          fi

      - name: "提交文件更新"
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Fetch API data for TeStore accelerations"

      - name: "同步Gitee镜像"
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/jzwalk
          dst: gitee/jzwalk
          dst_key: ${{ secrets.SYNC_PV }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "API_Mirror"
          force_update: true
