# 将所需API数据同步下载为GitHub文件供jsDelivr等镜像服务加速读取

name: "推送后自动更新数据文件"

on:
  push:
    branches:
      - "master"

jobs:

  download-api:
    name: "下载API数据至文件"
    runs-on: "ubuntu-latest"

    steps:
        uses: actions/checkout@v2

      - name: "读取TeStore加速目录内容"
        id: get_api_data
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/contents/ZIP_CDN
          repository: typecho-fans/plugins
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "输出TeStore加速数据内容"
        run: |
          echo "${{ steps.get_api_data.outputs.data }}" > zip_cdn.json

      - name: "读取TeStore最后提交记录"
        id: get_api_data
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/commits?per_page=1
          repository: typecho-fans/plugins
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "输出TeStore最后提交记录"
        run: |
          echo "${{ steps.get_api_data.outputs.data }}" > last_commit.json

      - name: "提交所有数据文件更新"
        uses: EndBug/add-and-commit@v4
        with:
          author_name: 羽中
          author_email: zyz59@126.com
          message: "更新各项API数据"
          add: "*.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
