# 将API数据下载为文件供Gitee/jsDelivr等镜像地址加速

name: "接收触发信号更新文件"

on:
  repository_dispatch:
    types: [sync]

jobs:

  download-api:
    name: "输出API数据至文件"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: "输出ZIP_CDN加速目录数据"
        run: |
          curl -s https://api.github.com/repos/typecho-fans/plugins/contents/ZIP_CDN > zip_cdn.json

      - name: "输出收录计数和推送时间戳"
        run: |
          echo '{"total": "${{ github.event.client_payload.total }}", "update": "${{ github.event.client_payload.update }}"}' > info.json

      - name: "提交数据文件更新"
        uses: EndBug/add-and-commit@v4
        with:
          add: "*.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "同步Gitee镜像目录"
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/jzwalk
          dst: gitee/jzwalk
          dst_key: ${{ secrets.SYNC_PV }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "API_Mirror"
          force_update: true

      - name: "自动部署Gitee Page"
        uses: yanglbme/gitee-pages-action@master
        with:
          gitee-username: jzwalk
          gitee-password: ${{ secrets.GITEE_PW }}
          gitee-repo: jzwalk/API_Mirror
          https: true
