# 将API数据下载为GitHub文件供jsDelivr等镜像服务加速

name: "接收信号触发文件更新"

on:
  repository_dispatch:
    types: [sync]

jobs:

  download-api:
    name: "输出API数据至文件"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: "输出TeStore加速目录数据"
        run: |
          curl -s https://api.github.com/repos/typecho-fans/plugins/contents/ZIP_CDN > zip_cdn.json

      - name: "输出TeStore最后提交数据"
        run: |
          curl -s https://api.github.com/repos/typecho-fans/plugins/commits?per_page=1 > last_commit.json

      - name: "提交数据文件更新"
        uses: EndBug/add-and-commit@v4
        with:
          author_name: 羽中
          author_email: zyz59@126.com
          message: "更新各项API数据"
          add: "*.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
