# 检测外部登记GitHub插件版本并同步更新发布zip包

name: "手动测试触发更新脚本"

on:
  workflow_dispatch

jobs:

  auto-update:
    name: "自动更新GitHub插件"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: "执行PHP脚本"
        run: |
          php auto-update.php

      - name: "提交更新文件"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto update GitHub plugins in TESTORE.md"

      - name: "上传操作记录"
        uses: actions/upload-artifact@v2
        with:
          name: "updates-log"
          path: /home/runner/work/API_Mirror/TMP/updates.log

      - name: "匹配压缩包名"
        id: match-con
        run: |
          find /home/runner/work/API_Mirror/TMP/NEW -type f -name "[a-cA-C]*"
          echo "::set-output name=A2C::$?"
          find /home/runner/work/API_Mirror/TMP/NEW -type f -name "[m-rM-R]*"
          echo "::set-output name=M2R::$?"
          find /home/runner/work/API_Mirror/TMP/NEW -type f -name "[s-zS-Z]*"
          echo "::set-output name=S2Z::$?"

      - name: "发布压缩包A-C"
        uses: svenstaro/upload-release-action@v2
        if: steps.match-con.outputs.A2C != '0'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/API_Mirror/TMP/NEW/[a-cA-C]*
          tag: "plugins-A_to_C"
          overwrite: true
          file_glob: true

      - name: "发布压缩包M-R"
        uses: svenstaro/upload-release-action@v2
        if: steps.match-con.outputs.M2R != '0'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/API_Mirror/TMP/NEW/[m-rM-R]*
          tag: "plugins-M_to_R"
          overwrite: true
          file_glob: true

      - name: "发布压缩包S-Z"
        uses: svenstaro/upload-release-action@v2
        if: steps.match-con.outputs.S2Z != '0'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/API_Mirror/TMP/NEW/[s-zS-Z]*
          tag: "plugins-S_to_Z"
          overwrite: true
          file_glob: true
