name: "Actions执行后同步数据"

on:
  workflow_dispatch

jobs:

  api-mirror:
    name: "下载API并推送Gitee"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4

      - name: "ZIP_CDN数据"
        run: |
          curl -s https://api.github.com/repos/typecho-fans/plugins/contents/ZIP_CDN > ZIP_CDN.json

      - name: "文档变更时间"
        run: |
          date_testore=`curl -s "https://api.github.com/repos/typecho-fans/plugins/commits?path=TESTORE.md&page=1&per_page=1" | jq -r ".[0].commit.committer.date"`
          date_readme=`curl -s "https://api.github.com/repos/typecho-fans/plugins/commits?path=README.md&page=1&per_page=1" | jq -r ".[0].commit.committer.date"`
          if [[ $date_testore > $date_readme ]]; then
            echo $date_testore > UD_TIME.json
          else
            echo $date_readme > UD_TIME.json
          fi

      - name: "提交文件更新"
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Fetch API data & sync repo to Gitee for TeStore accelerations"

      - name: "同步Gitee镜像"
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/jzwalk
          dst: gitee/jzwalk
          dst_key: ${{ secrets.SYNC_PV }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "API_Mirror"
          force_update: true
