name: "基于其他Action触发"

on:
  workflow_run:
    workflows:
      - "手动更新单GitHub插件"
      - "定时更新全GitHub插件"
      - "推送更新变动GitHub插件"
    branches:
      - "master"
    types:
      - completed

jobs:

  dispatch-mirror:
    name: "其他workflow完成时"
    runs-on: "ubuntu-latest"
    if: curl -s https://github.com/jzwalk/API_Mirror/commit/master.diff | grep "+++ b/TESTORE.md"

    steps:
      - run: |
          if curl -s https://github.com/jzwalk/API_Mirror/commit/master.diff | grep "+++ b/TESTORE.md"
            then
              echo "1"
          else
              echo "0"
          fi
