name: "基于其他Action触发"

on:
  workflow_run:
    workflows:
      - "手动更新单GitHub插件"
    branches:
      - "master"
    types:
      - completed

jobs:

  dispatch-mirror:
    name: "其他workflow完成时"
    runs-on: "ubuntu-latest"

    steps:
      - run: |
          stamp=`date +%s`
          echo "$stamp"
