name: "基于其他Action触发"

on:
  workflow_run:
    workflows:
      - "手动更新单GitHub插件"
      - "定时更新全GitHub插件"
      - "推送更新变动GitHub插件"
    branches:
      - "master"
    types:
      - completed

jobs:

  test-md:
    name: "检测最近提交"
    runs-on: "ubuntu-latest"
    outputs:
      isMD: ${{ steps.grep-diff.outputs.result }}
    steps:
      - id: grep-diff
        run: |
          hash=`git log -n 1 --pretty | grep Merge | head -1 | awk '{print $2}'` && name="$hash" || name="master"
          if curl -s https://github.com/jzwalk/API_Mirror/commit/"$name".diff | grep "+++ b/TESTORE.md"
            then
              echo "::set-output name=result::1"
          else
              echo "::set-output name=result::"
          fi

  dispatch-mirror:
    name: "其他workflow完成时"
    runs-on: "ubuntu-latest"
    needs: test-md
    if: needs.test-md.outputs.isMD

    steps:
      - run: |
          echo "${{ needs.test-md.outputs.isMD }}"
