name: "手动更新单Gitee插件"

on: 
  workflow_dispatch:
#    inputs:
#      repo-git:
#        description: "Gitee插件克隆地址"
#        required: true
#        default: 'https://gitee.com/user/repo.git'

jobs:

  test-update:
    name: "手动更新Gitee插件"
    runs-on: "ubuntu-latest"

    steps:
#      - run: |
#          git clone ${{ github.event.inputs.repo-git }}

#      - run: |
#          ls

      - run: |
          php TEST-UPDATE.php