name: "手动更新单Gitee插件"

on: 
  workflow_dispatch:
    inputs:
      repo-git:
        description: "Gitee插件克隆地址"
        required: true
        default: 'https://gitee.com/user/repo.git'

jobs:

  test-update:
    name: "手动更新Gitee插件"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - run: |
          php TEST-UPDATE.php ${{ github.event.inputs.repo-git }}

      - run: |
          ls /home/runner/work/API_Mirror/GITEE

      - name: "提交更新文件"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Test: auto update plugins"
