# 检测外部登记GitHub插件版本信息并下载加速用zip包

name: "手动测试触发更新脚本"

on:
  workflow_dispatch

jobs:

  auto-update:
    name: "自动更新GitHub插件"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: "执行PHP脚本"
        run: |
          php auto-update.php > updates.log

      - name: "提交更新文件"
        uses: stefanzweifel/git-auto-commit-action@v4
