name: "手动更新单Gitee插件"

on: 
  workflow_dispatch:
    inputs:
      repo-git:
        description: "Gitee插件目录地址(结尾勿带'/'号)"
        required: true
        default: 'https://gitee.com/user/repo'

jobs:

  test-update:
    name: "手动更新Gitee插件"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - run: |
          php AUTO-UPDATE.php ${{ secrets.GITHUB_TOKEN }} ${{ github.event.inputs.repo-git }}

      - name: "提交更新文件"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Test: auto update plugins"
